changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Features
      labels:
        - feat
        - enhancement
    - title: Bug Fixes
      labels:
        - fix
        - bug
    - title: Tests
      labels:
        - test
        - testing
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: Other
      labels:
        - "*"
