apiVersion: v1
kind: Namespace
metadata:
  name: corso-system
  labels:
    app.kubernetes.io/name: corso
    app.kubernetes.io/part-of: corso
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: corso
  namespace: corso-system
  labels:
    app.kubernetes.io/name: corso
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: corso
  labels:
    app.kubernetes.io/name: corso
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["bpfwatch.io"]
    resources: ["bpfprogramallowlists"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: corso
  labels:
    app.kubernetes.io/name: corso
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: corso
subjects:
  - kind: ServiceAccount
    name: corso
    namespace: corso-system
