//go:build !ignore_autogenerated

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties into another BPFProgramAllowlist.
func (in *BPFProgramAllowlist) DeepCopyInto(out *BPFProgramAllowlist) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of BPFProgramAllowlist.
func (in *BPFProgramAllowlist) DeepCopy() *BPFProgramAllowlist {
	if in == nil {
		return nil
	}
	out := new(BPFProgramAllowlist)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as runtime.Object.
func (in *BPFProgramAllowlist) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another BPFProgramAllowlistList.
func (in *BPFProgramAllowlistList) DeepCopyInto(out *BPFProgramAllowlistList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BPFProgramAllowlist, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of BPFProgramAllowlistList.
func (in *BPFProgramAllowlistList) DeepCopy() *BPFProgramAllowlistList {
	if in == nil {
		return nil
	}
	out := new(BPFProgramAllowlistList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as runtime.Object.
func (in *BPFProgramAllowlistList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another BPFProgramAllowlistSpec.
func (in *BPFProgramAllowlistSpec) DeepCopyInto(out *BPFProgramAllowlistSpec) {
	*out = *in
	if in.IgnoreKnownDaemons != nil {
		in, out := &in.IgnoreKnownDaemons, &out.IgnoreKnownDaemons
		*out = new(bool)
		**out = **in
	}
	if in.Programs != nil {
		in, out := &in.Programs, &out.Programs
		*out = make([]AllowedProgramSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of BPFProgramAllowlistSpec.
func (in *BPFProgramAllowlistSpec) DeepCopy() *BPFProgramAllowlistSpec {
	if in == nil {
		return nil
	}
	out := new(BPFProgramAllowlistSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another AllowedProgramSpec.
func (in *AllowedProgramSpec) DeepCopyInto(out *AllowedProgramSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of AllowedProgramSpec.
func (in *AllowedProgramSpec) DeepCopy() *AllowedProgramSpec {
	if in == nil {
		return nil
	}
	out := new(AllowedProgramSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another BPFProgramAllowlistStatus.
func (in *BPFProgramAllowlistStatus) DeepCopyInto(out *BPFProgramAllowlistStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy returns a deep copy of BPFProgramAllowlistStatus.
func (in *BPFProgramAllowlistStatus) DeepCopy() *BPFProgramAllowlistStatus {
	if in == nil {
		return nil
	}
	out := new(BPFProgramAllowlistStatus)
	in.DeepCopyInto(out)
	return out
}
