// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package enforcer

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadBpfLsm returns the embedded CollectionSpec for bpf_lsm.
func loadBpfLsm() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfLsmBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf_lsm: %w", err)
	}

	return spec, err
}

// loadBpfLsmObjects loads bpf_lsm and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfLsmObjects
//	*bpfLsmPrograms
//	*bpfLsmMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfLsmObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpfLsm()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfLsmSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfLsmSpecs struct {
	bpfLsmProgramSpecs
	bpfLsmMapSpecs
	bpfLsmVariableSpecs
}

// bpfLsmProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfLsmProgramSpecs struct {
	EnforceBpfProgLoad *ebpf.ProgramSpec `ebpf:"enforce_bpf_prog_load"`
}

// bpfLsmMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfLsmMapSpecs struct {
	AllowedProgs   *ebpf.MapSpec `ebpf:"allowed_progs"`
	EnforceEvents  *ebpf.MapSpec `ebpf:"enforce_events"`
}

// bpfLsmVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfLsmVariableSpecs struct {
	EnforcementMode *ebpf.VariableSpec `ebpf:"enforcement_mode"`
}

// bpfLsmObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfLsmObjects struct {
	bpfLsmPrograms
	bpfLsmMaps
	bpfLsmVariables
}

func (o *bpfLsmObjects) Close() error {
	return _BpfLsmClose(
		&o.bpfLsmPrograms,
		&o.bpfLsmMaps,
	)
}

// bpfLsmMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfLsmMaps struct {
	AllowedProgs  *ebpf.Map `ebpf:"allowed_progs"`
	EnforceEvents *ebpf.Map `ebpf:"enforce_events"`
}

func (m *bpfLsmMaps) Close() error {
	return _BpfLsmClose(
		m.AllowedProgs,
		m.EnforceEvents,
	)
}

// bpfLsmVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfLsmVariables struct {
	EnforcementMode *ebpf.Variable `ebpf:"enforcement_mode"`
}

// bpfLsmPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfLsmPrograms struct {
	EnforceBpfProgLoad *ebpf.Program `ebpf:"enforce_bpf_prog_load"`
}

func (p *bpfLsmPrograms) Close() error {
	return _BpfLsmClose(
		p.EnforceBpfProgLoad,
	)
}

func _BpfLsmClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_lsm_bpfel.o
var _BpfLsmBytes []byte
