// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package auditor

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadBpf_monitor returns the embedded CollectionSpec for bpf_monitor.
func loadBpf_monitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Bpf_monitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf_monitor: %w", err)
	}

	return spec, err
}

// loadBpf_monitorObjects loads bpf_monitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpf_monitorObjects
//	*bpf_monitorPrograms
//	*bpf_monitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpf_monitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf_monitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpf_monitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_monitorSpecs struct {
	bpf_monitorProgramSpecs
	bpf_monitorMapSpecs
	bpf_monitorVariableSpecs
}

// bpf_monitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_monitorProgramSpecs struct {
	TraceBpfProgLoad *ebpf.ProgramSpec `ebpf:"trace_bpf_prog_load"`
}

// bpf_monitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_monitorMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// bpf_monitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_monitorVariableSpecs struct {
}

// bpf_monitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpf_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_monitorObjects struct {
	bpf_monitorPrograms
	bpf_monitorMaps
	bpf_monitorVariables
}

func (o *bpf_monitorObjects) Close() error {
	return _Bpf_monitorClose(
		&o.bpf_monitorPrograms,
		&o.bpf_monitorMaps,
	)
}

// bpf_monitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpf_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_monitorMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *bpf_monitorMaps) Close() error {
	return _Bpf_monitorClose(
		m.Events,
	)
}

// bpf_monitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpf_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_monitorVariables struct {
}

// bpf_monitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpf_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_monitorPrograms struct {
	TraceBpfProgLoad *ebpf.Program `ebpf:"trace_bpf_prog_load"`
}

func (p *bpf_monitorPrograms) Close() error {
	return _Bpf_monitorClose(
		p.TraceBpfProgLoad,
	)
}

func _Bpf_monitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_monitor_bpfeb.o
var _Bpf_monitorBytes []byte
