// Code generated by bpf2go; DO NOT EDIT.
// This is a stub for compilation without clang/bpf2go.
// Run "go generate" to produce the real implementation.

package auditor

import (
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpf_monitorPrograms struct {
	TraceBpfProgLoad *ebpf.Program `ebpf:"trace_bpf_prog_load"`
}

type bpf_monitorMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

type bpf_monitorObjects struct {
	bpf_monitorPrograms
	bpf_monitorMaps
}

func loadBpf_monitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	coll, err := loadBpf_monitorCollection(opts)
	if err != nil {
		return err
	}

	if err := coll.Assign(obj); err != nil {
		return fmt.Errorf("assigning bpf_monitor objects: %w", err)
	}
	return nil
}

func loadBpf_monitorCollection(opts *ebpf.CollectionOptions) (*ebpf.Collection, error) {
	return nil, fmt.Errorf("bpf_monitor BPF program not compiled: run go generate first")
}

func (o *bpf_monitorObjects) Close() error {
	return closeObjects(o)
}

func closeObjects(closers ...interface{ Close() error }) error {
	var errs []error
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			errs = append(errs, err)
		}
	}
	if len(errs) > 0 {
		return fmt.Errorf("closing objects: %v", errs)
	}
	return nil
}

// Satisfy unused import
var _ io.Reader
