apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "corso.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "corso.labels" . | nindent 4 }}
data:
  CORSO_WEBHOOK_URL: {{ .Values.webhook.url | quote }}
  CORSO_WEBHOOK_TIMEOUT: {{ .Values.webhook.timeout | quote }}
  CORSO_CONTROLLER_ENABLED: {{ .Values.controller.enabled | quote }}
