{{- if .Values.controller.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "corso.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "corso.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "corso.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        {{- include "corso.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: controller
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "corso.serviceAccountName" . }}
      containers:
        - name: controller
          image: {{ include "corso.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/corso", "--controller-only"]
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
          envFrom:
            - configMapRef:
                name: {{ include "corso.fullname" . }}-config
          env:
            - name: CORSO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: {{ .Values.agent.metricsPort }}
              name: metrics
              protocol: TCP
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.agent.metricsPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.agent.metricsPort }}
            initialDelaySeconds: 3
            periodSeconds: 5
{{- end }}
