apiVersion: v1
kind: Service
metadata:
  name: {{ include "corso.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "corso.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.agent.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "corso.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent
